name: test
on: 
   push:
   workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install Dependencies
        run: npm ci
      - name: run test
        run: npm test
        env:
          CODA_API_TOKEN: ${{ secrets.CODA_API_TOKEN }}


